[package]
name = "concolor-clap"
version = "0.0.6"
license = "MIT OR Apache-2.0"
description = "Clap mixin to control console colors"
repository = "https://github.com/rust-cli/concolor"
categories = ["command-line-interface"]
keywords = ["cli", "color", "no-std", "terminal", "ansi"]
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[features]
default = ["auto"]
auto = ["concolor-control/auto", "clap/color"]
api_unstable = ["concolor-control/api_unstable"]

[dependencies]
concolor-control = { version = "^0.0.7", path = "../control", default-features = false }
clap = { version = "3.0", default-features = false, features = ["std", "derive"] }
