[package]
name = "concolor-clap"
version = "0.0.3"
license = "MIT OR Apache-2.0"
description = "Clap mixin to control console colors"
repository = "https://github.com/rust-cli/concolor"
categories = ["command-line-interface"]
keywords = ["cli", "color", "no-std", "terminal", "ansi"]
edition = "2018"

[features]
default = ["auto"]
auto = ["concolor-control/auto"]

[dependencies]
# Let the application decide what features to enable
structopt = { version = "0.3", default-features = false }
concolor-control = { version = "^0.0.3", path = "../control", default-features = false }
